# Generated by Django 4.2.10 on 2024-02-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="ingredient",
            field=models.CharField(max_length=200),
        ),
    ]
